name: grpc_bchrpc_web
version: 0.1.0
description: Connect to a BCHD full node with a simplified grpc-web client wrapper.
homepage: https://github.com/simpleledgerinc/grpc-bchrpc-dart-web
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  grpc: ^3.0.0
  protobuf: ^2.0.0
  fixnum: ^1.0.0
dev_dependencies:
  test: ^1.17.1
  convert: ^3.0.0
