name: grpc_bchrpc_web
version: 0.0.1
description: Connect to a BCHD full node with a simplified grpc-web client wrapper.
homepage: https://github.com/simpleledgerinc/grpc-bchrpc-dart-web
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  grpc: ^2.3.0
  protobuf: ^1.0.1
  fixnum: ^0.10.11
dev_dependencies:
  test: ^1.14.2
  convert: ^2.1.1
